name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `turbo xxx --filter` commands
        uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build Monorepo
        run: pnpm run build --filter=[${{ env.NX_HEAD }}...${{ env.NX_BASE }}]

      - name: Lint Monorepo
        run: pnpm run lint --filter=scope...[${{ env.NX_HEAD }}...${{ env.NX_BASE }}]

      - name: Test Monorepo
        run: pnpm run test
